import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import LeftSideBar from "@/components/LeftSideBar";
import { Poppins } from "next/font/google";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins antialiased`}>
        <div className=" flex min-h-screen  ">
         <LeftSideBar />
          <section className="flex min-h-screen flex-1 flex-col overflow-hidden">
            {children}
          </section>
        </div>
      </body>
    </html>
  );
}
